{"uuid": "b09a0446-af13-49b2-b988-4bbd60344679", "children": ["e672db47-80c1-49a3-81c4-d352f2b41ee2", "52e8ed26-5515-47d0-9495-01d2efec33ef"], "befores": [{"name": "_Class__pytest_setup_class", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '/home/amarm/repositories/AddressBook/new_test_suite\\\\..\\\\test_input_data\\\\qa.json'\n", "trace": "  File \"/home/amarm/repositories/AddressBook/venv/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/amarm/repositories/AddressBook/venv/lib/python3.7/site-packages/_pytest/fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/amarm/repositories/AddressBook/venv/lib/python3.7/site-packages/_pytest/fixtures.py\", line 908, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/amarm/repositories/AddressBook/venv/lib/python3.7/site-packages/_pytest/python.py\", line 799, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"/home/amarm/repositories/AddressBook/venv/lib/python3.7/site-packages/_pytest/python.py\", line 732, in _call_with_optional_argument\n    func(arg)\n  File \"/home/amarm/repositories/AddressBook/new_test_suite/test_add_address_negative_setup_parametrize.py\", line 15, in setup_class\n    cls.file = open(f\"{cur_path}\\\\..\\\\test_input_data\\\\qa.json\")\n"}, "start": 1613387454249, "stop": 1613387454250}], "start": 1613387454249, "stop": 1613387454310}